### PR TITLE
Improve documentation and examples (fixes #36)

### LINKED ISSUE #36: Fix documentation
As described in https://github.com/hamstar/Wikimate/pull/34#issuecomment-251193934

### PR DESCRIPTION
**Pull request by Xymph**
See #36. The try/catch block around `login()` isn't needed as that method (nor the underlying `Request_Session` call) can't generate exceptions. The remaining commits add/update all aspects in the documentation that I can think of now.

### CODE REVIEW

**Comment by waldyrious** [comment]
Did you miss [this one](https://github.com/hamstar/Wikimate/issues/36#issuecomment-251473275)?

**Comment by Xymph** [comment]
[Nope](https://github.com/hamstar/Wikimate/issues/36#issuecomment-252363268). :smile:

**Comment by waldyrious** [comment]
Ok, I think we're all set! Merge time :)

**Comment by Xymph** [comment]
On GitHub, there's no time like merge time. :+1:

**Pull request merged**
