### PR TITLE
Requests support, md5 issue and Mediawiki conflict avoidance

### PR DESCRIPTION
**Pull request by devlet**
Changes:

* Support all Requests constructor arguments
* Comment out md5 param that gives connection errors
* Use WikimatePage class name instead of WikiPage to avoid conflict with Mediawiki

### CODE REVIEW

**Comment by waldyrious** [comment]
Thanks for the contribution! I believe it would be ideal if @Xymph or @hamstar reviewed this, since any php skills I might have had in the past are pretty much gone by now. Hopefully one of them can find the availability to look at this sometime soon :)

**Comment by Xymph** [comment]
Indeed, thanks. I'm a little rusty on this github stuff too :wink:  but I took a look at it. As a general observation, three unrelated commits in one PR doesn't follow our [Governance](https://github.com/hamstar/Wikimate/blob/master/GOVERNANCE.md) guideline 3, but for small changes by a first-time contributor that's okay. :+1: 
Further, I put some comments and questions on the individual commits.

**Comment by devlet** [comment]
Sorry to put everything into the same basket. Shall instead I open one pull request per commit/change?

**Comment by Xymph** [comment]
Not yet, it may depend on the outcome of the other topics above. Perhaps you can answer my questions about them?

**Comment by Xymph** [comment]
@devlet, given the lack of progress on this PR and my questions, yes, it would help if you submit 
de46d39 + 2ee8c09 in a separate PR which can be easily accepted. This PR would then be rejected and closed.

**Comment by Xymph** [comment]
The accepted changes for supporting Requests constructor arguments have been cherry-picked into PR #93 and merged.
Rejecting and closing this PR.

**Pull request closed without merging**
