### PR TITLE
Switch methods and variables from private to protected

### PR DESCRIPTION
**Pull request by devlet**
Switch methods and variables from private to protected so the class be be easily extended.

### CODE REVIEW

**Comment by samwilson** [comment]
Sounds like a sensible idea. Makes it easier to customise the classes.

**Comment by waldyrious** [comment]
@samwilson thanks for the review. Since @hamstar appears to be absent, I'll merge the PR. @devlet sorry for the long wait!

**Comment by samwilson** [comment]
Thanks @waldyrious :) that was quick!

Are you maintaining this package now? In @hamstar 's absence? Any plans for it?

I've got some ideas about features I'd love to add, such as a category traversal system. Would you be interested in PRs?

**Comment by waldyrious** [comment]
@samwilson I made a couple contributions a while ago and @hamstar gave me commit rights. However, I can't maintain it properly, as I don't work with PHP (or Wikimate) regularly. 

That said, you can surely send PRs, but I'm afraid I won't be a good person to review them. I suppose it would be best if you could ping other people who could do a proper review of your changes.

Alternatively, if you feel like it, you could add reasonably detailed descriptions of the changes to the commit messages (and/or PR comments). I believe my involvement in such discussions would have the added benefit of showing where documentation or code readability may be lacking, which would make Wikimate's code more newbie-friendly :)

So, lots of options -- feel free to pick what seems best to you!

**Comment by samwilson** [comment]
Hm, okay, well I'll have a play and send a PR or two and we can take it from there. I'm not sure how much time I'll have for this, but I might be using it for work in which case it'd be certainly something I'd be interested in helping with. :-)

**Comment by waldyrious** [comment]
Sure, it's up to you. Any contribution in welcome :)

**Pull request merged**
