### PR TITLE
Update API URLs to typical path, update other links, and use https

### PR DESCRIPTION
**Pull request by Xymph**
I noticed a few http links now redirect to https, and an extended URL scan pointed to some other links also worth updating.

### CODE REVIEW

**Comment by Xymph** [comment]
Hmm, looks like markdownlint needs to be taught how to accept our changelog.

**Comment by Xymph** [comment]
Hey @waldyrious, could you please resolve this GH action problem? Thanks.

**Comment by waldyrious** [comment]
Hmm, it seems they [changed](https://github.com/DavidAnson/markdownlint/commit/f2725178b1e83b07d7f7cc2db64d42f6aa14b8a1) the configuration of MD024 to only accept `siblings_only` rather than `allow_different_nesting`, which is what we used.

We need to change this code:

https://github.com/hamstar/Wikimate/blob/e6d3fdac49ab87f18e96c800658ce32d5eb5b388/.markdownlint.yml#L21-L24

```diff
 # MD024/no-duplicate-heading
 MD024:
   # Only check sibling headings
-  allow_different_nesting: true
+  siblings_only: true
```

Do you want to do that in this PR, or should we make it a separate one?

**Comment by Xymph** [comment]
Welcome back. The clean way would be a separate PR, tbh.

**Comment by Xymph** [comment]
@waldyrious The silence has been deafening long enough. :stuck_out_tongue_winking_eye: 

I fixed the markdown rule in this PR and merged it per the Governance rule 2 exception.

**Pull request merged**
